# Bundle the dependency so we can easily load from CDN
# https://github.com/gram-js/gramjs (MIT Licensed)
name: Bundle Dependency

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'View list of files that will be published before the real release'
        required: true
        default: 'true' ## Dry run
  release:
    # This specifies that the build will be triggered when we publish a release
    types: [published]

jobs:
  build:
    name: Bundle Dependency
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Usually this will be finish under 5 minutes

    steps:
      - uses: actions/checkout@v2

      - name: ⚙ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: 🛠 Bundling Modules
        run: npm run build-gramjs

      - run: npm version ${{ github.event.release.tag_name }}-dep
      - run: mv ./gramjs/browser/ ./dist/browser/

      - name: 📦 Dry Run
        if: github.event.inputs.dryRun == 'true'
        run: npm publish --dry-run

      # If you want to publish to NPM, make sure to put your NPM token to repository settings
      - name: 📦 Publish Packages
        if: github.event.inputs.dryRun != 'true'
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}